### ISSUE TITLE
Port SolidPolygonLayer

### ISSUE THREAD

**Issue by ibgreen** [UnfoldedInc/deck.gl-native#107]
We need to port the [`SolidPolygonLayer`](https://github.com/visgl/deck.gl/tree/master/modules/layers/src/solid-polygon-layer)

Compare with e.g. LineLayer and ScatterplotLayer to see how they were ported.

For initial port, ignore tesselation, just port props, basic layer functions and shaders.

**Comment by ibgreen** [comment]
@Pessimistress @ilijapuaca Assuming you have not started on this, assigning to @randypalusz

**Comment by ilijapuaca** [comment]
Working implementation introduced with #145
