### ISSUE TITLE
Implement tesselation/loading variable-size arrays for SolidPolygonLayer

### ISSUE THREAD

**Issue by randypalusz** [UnfoldedInc/deck.gl-native#135]
From @ilijapuaca:

[SolidPolygonLayer](https://github.com/visgl/deck.gl/tree/4997ca04768d291950495e9edfb9cb3f927359e1/modules/layers/src/solid-polygon-layer)

In [data-column.js](https://github.com/visgl/deck.gl/blob/bbbf0800741887fecc559d624cef03583c91c9d6/modules/core/src/lib/attribute/data-column.js), I can see a mention of nextPosition and noting it uses vertexOffset to get that attribute. There’s also a mention of it in [polygon-tessalator.js](https://github.com/visgl/deck.gl/blob/4997ca04768d291950495e9edfb9cb3f927359e1/modules/layers/src/solid-polygon-layer/polygon-tesselator.js).

I assume that once tessellation is done on raw array coming from the data set, we’d get another array of vertices that we then need to iterate over. Instead of splitting this up “start” and “end” vertices like we do for line layer, we iterate over this array of vertices, using these offsets in order to pick out the right segments.

This would obviously require putting a few things in place that we currently don’t support, like offsets, which depending on how much work it is may not be something we want to do right now. Perhaps there’s a simpler way for us to format this data so that it can be used in the same way.

The other thing we’ll need support for is loading variable size arrays in order to parse that data set. That should hopefully be pretty straight-forward, as we can reuse most of the functionality that getVectorX has in [row.h](https://github.com/UnfoldedInc/deck.gl-native/blob/master/cpp/modules/deck.gl/core/src/arrow/row.h)

**Comment by ibgreen** [comment]
@Pessimistress who has done most of the recent work on the `PolygonLayer` - just for awareness that polygon tesselation is being worked through.

**Comment by ilijapuaca** [comment]
Implemented as part of `SolidPolygonLayer` effort, final updates were made in #145
